require("sndp.plugins-setup")
require("sndp.core.options")
require("sndp.core.keymaps")
require("sndp.core.colorscheme")
require("sndp.plugins.nvim-tree")
require("sndp.plugins.lualine")
require("sndp.plugins.colorizer")
require("sndp.plugins.mason")
require("sndp.plugins.lsp_config")
require("sndp.plugins.completions")
require("sndp.plugins.telescope")
require("sndp.plugins.treesitter")

